name: Testing Set Env
on:
  push:
    branches:
      - develop
      - master
jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.get-env.outputs.result }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Environment Name
        id: get-env
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const ref = context.ref;
            let environment;
            switch(ref) {
              case 'refs/heads/master':
                environment = 'prod';
                break;
              case 'refs/heads/develop':
              default:
                environment = 'dev';
            }
            return environment;

      - name: Display Environment Variable
        run: echo "ENV is ${{ steps.get-env.outputs.result }}"

  build:
    needs: set-environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.set-environment.outputs.environment_name }}

    steps:

      - name: Checkout Code Again
        uses: actions/checkout@v2

      - name: Run Build Steps
        run: |
          echo "Environment is : $GITHUB_ENV"
          echo "Vars are ${{ vars }}"



