name: Testing Set Env
on:
  push:
    branches:
      - develop
      - master
  workflow_dispatch:
jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.get-env.outputs.result }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Environment Name
        id: get-env
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const ref = context.ref;
            let environment;
            switch(ref) {
              case 'refs/heads/master':
                environment = 'prod';
                break;
              case 'refs/heads/develop':
              default:
                environment = 'dev';
            }
            return environment;

      - name: Display Environment Variable
        run: echo "ENV is ${{ steps.get-env.outputs.result }}"

  build:
    needs: set-environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.set-environment.outputs.environment_name }}
    env:
      BUILD_ENV: ${{ vars.BUILD_ENV }}

    steps:
      - name: Checkout Code Again
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Build Steps
        run: |
          echo "BUILD_ENV is $BUILD_ENV"
          npm run check-env